<?php

namespace AppBundle\Repository;

/**
 * disponibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class disponibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
