<?php

namespace AppBundle\Repository;

/**
 * StudentLanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentLanguagesRepository extends \Doctrine\ORM\EntityRepository
{
}
